export interface KnowledgeSource {
  id: string;
  name: string;
  category: 'Biomedical & Clinical' | 'Open Government & Public Data' | 'Planetary & Environment' | 'Science, Research & Tech';
  description: string;
  url: string;
  status: 'online' | 'syncing' | 'offline';
  itemsCount: string;
  isPrimaryForDDI?: boolean;
}

export const KNOWLEDGE_SOURCES: KnowledgeSource[] = [
  // 1. Biomedical & Clinical Health (Primary for Drug-Drug Interaction Safety)
  {
    id: 'pubmed',
    name: 'PubMed / NCBI',
    category: 'Biomedical & Clinical',
    description: '36+ million biomedical literature citations and clinical trial pharmacology abstracts.',
    url: 'https://pubmed.ncbi.nlm.nih.gov/',
    status: 'online',
    itemsCount: '36.8M papers',
    isPrimaryForDDI: true,
  },
  {
    id: 'who-data',
    name: 'WHO Data Hub',
    category: 'Biomedical & Clinical',
    description: 'World Health Organization global health data, pharmacovigilance, and essential medicine lists.',
    url: 'https://data.who.int/',
    status: 'online',
    itemsCount: '2,400+ indicators',
    isPrimaryForDDI: true,
  },
  {
    id: 'who-gho',
    name: 'Global Health Observatory',
    category: 'Biomedical & Clinical',
    description: 'Comprehensive statistics and surveillance on global disease burden and pharmacological interventions.',
    url: 'https://www.who.int/data/gho',
    status: 'online',
    itemsCount: '1,000+ data sets',
    isPrimaryForDDI: true,
  },
  {
    id: 'india-ogd',
    name: 'India Open Government Data',
    category: 'Biomedical & Clinical',
    description: 'CDSCO, IPC Pharmacopoeia, and Ministry of Health public drug formulary data.',
    url: 'https://www.data.gov.in/',
    status: 'online',
    itemsCount: '580K+ resources',
    isPrimaryForDDI: true,
  },
  {
    id: 'our-world-in-data',
    name: 'Our World in Data',
    category: 'Biomedical & Clinical',
    description: 'Global health research, epidemiological trends, and life expectancy analytics.',
    url: 'https://ourworldindata.org/',
    status: 'online',
    itemsCount: '3,800+ charts',
  },

  // 2. Science, Research & Tech
  {
    id: 'arxiv',
    name: 'arXiv Research Repository',
    category: 'Science, Research & Tech',
    description: 'Open-access scientific papers in computer science, quantitative biology, and computational health.',
    url: 'https://arxiv.org/',
    status: 'online',
    itemsCount: '2.4M preprints',
  },
  {
    id: 'openalex',
    name: 'OpenAlex Scholarly Graph',
    category: 'Science, Research & Tech',
    description: 'Massive open scientific research graph mapping scholarly publications and authors worldwide.',
    url: 'https://openalex.org/',
    status: 'online',
    itemsCount: '250M+ scientific works',
    isPrimaryForDDI: true,
  },
  {
    id: 'crossref',
    name: 'Crossref Metadata',
    category: 'Science, Research & Tech',
    description: 'Digital object identifier metadata linking peer-reviewed pharmacological journals.',
    url: 'https://www.crossref.org/',
    status: 'online',
    itemsCount: '150M+ records',
  },
  {
    id: 'wikidata',
    name: 'Wikidata Semantic Graph',
    category: 'Science, Research & Tech',
    description: 'Structured public knowledge base containing extensive pharmacology and chemical compound properties.',
    url: 'https://www.wikidata.org/',
    status: 'online',
    itemsCount: '108M+ entities',
    isPrimaryForDDI: true,
  },
  {
    id: 'wikimedia-commons',
    name: 'Wikimedia Commons',
    category: 'Science, Research & Tech',
    description: 'Educational public-domain media, scientific anatomical diagrams, and molecular structures.',
    url: 'https://commons.wikimedia.org/',
    status: 'online',
    itemsCount: '102M+ media files',
  },
  {
    id: 'hackernews',
    name: 'Hacker News API',
    category: 'Science, Research & Tech',
    description: 'Real-time technology news, healthtech advancements, and community engineering discussions.',
    url: 'https://github.com/HackerNews/API',
    status: 'online',
    itemsCount: 'Real-time feed',
  },
  {
    id: 'github-events',
    name: 'GitHub Public Events',
    category: 'Science, Research & Tech',
    description: 'Open source bioinformatics, machine learning pipelines, and developer health repository activity.',
    url: 'https://docs.github.com/en/rest/activity/events',
    status: 'online',
    itemsCount: '10K events/hr',
  },
  {
    id: 'stackexchange',
    name: 'Stack Exchange API',
    category: 'Science, Research & Tech',
    description: 'Peer-reviewed community Q&A spanning Medical Sciences, Biology, and Chemistry.',
    url: 'https://api.stackexchange.com/',
    status: 'online',
    itemsCount: '22M+ questions',
  },

  // 3. Open Government & Public Data
  {
    id: 'data-gov',
    name: 'Data.gov (USA)',
    category: 'Open Government & Public Data',
    description: 'US federal open data portal including FDA openFDA, HHS, and CDC health datasets.',
    url: 'https://data.gov/',
    status: 'online',
    itemsCount: '250K+ datasets',
    isPrimaryForDDI: true,
  },
  {
    id: 'data-europa',
    name: 'data.europa.eu',
    category: 'Open Government & Public Data',
    description: 'Official European Union open data portal covering EMA pharmaceutical regulations.',
    url: 'https://data.europa.eu/',
    status: 'online',
    itemsCount: '1.6M+ datasets',
  },
  {
    id: 'eurostat',
    name: 'Eurostat',
    category: 'Open Government & Public Data',
    description: 'Statistical office of the European Union providing demographic and healthcare metrics.',
    url: 'https://ec.europa.eu/eurostat/',
    status: 'online',
    itemsCount: '5,500+ databases',
  },
  {
    id: 'world-bank',
    name: 'World Bank Open Data',
    category: 'Open Government & Public Data',
    description: 'Global economic, public health financing, and healthcare infrastructure statistics.',
    url: 'https://data.worldbank.org/',
    status: 'online',
    itemsCount: '16K+ indicators',
  },
  {
    id: 'un-news',
    name: 'UN News Global Feeds',
    category: 'Open Government & Public Data',
    description: 'United Nations global multilingual news, humanitarian health crises, and WHO directives.',
    url: 'https://news.un.org/en/rss',
    status: 'online',
    itemsCount: 'Live RSS feeds',
  },
  {
    id: 'cisa-alerts',
    name: 'CISA Security Advisories',
    category: 'Open Government & Public Data',
    description: 'Cybersecurity alerts protecting healthcare infrastructure and clinical health systems.',
    url: 'https://www.cisa.gov/news-events/cybersecurity-advisories',
    status: 'online',
    itemsCount: 'Live advisories',
  },
  {
    id: 'nvd-feeds',
    name: 'NVD Vulnerability Feeds',
    category: 'Open Government & Public Data',
    description: 'NIST National Vulnerability Database ensuring medical device software compliance.',
    url: 'https://nvd.nist.gov/vuln/data-feeds',
    status: 'online',
    itemsCount: '240K+ CVEs',
  },
  {
    id: 'loc',
    name: 'Library of Congress Digital',
    category: 'Open Government & Public Data',
    description: 'Historic pharmaceutical manuscripts, medical pharmacopeias, and public domain archives.',
    url: 'https://www.loc.gov/collections/',
    status: 'online',
    itemsCount: '175M+ items',
  },
  {
    id: 'smithsonian',
    name: 'Smithsonian Open Access',
    category: 'Open Government & Public Data',
    description: 'High-resolution historical scientific instruments and botanical medicinal collections.',
    url: 'https://www.si.edu/openaccess',
    status: 'online',
    itemsCount: '4.9M+ 2D/3D assets',
  },
  {
    id: 'met-museum',
    name: 'The Met Open Access',
    category: 'Open Government & Public Data',
    description: 'Metropolitan Museum of Art open collection images and historical apothecary artifacts.',
    url: 'https://www.metmuseum.org/art/collection',
    status: 'online',
    itemsCount: '492K+ artworks',
  },
  {
    id: 'osm',
    name: 'OpenStreetMap Global',
    category: 'Open Government & Public Data',
    description: 'Crowdsourced geographical map data for global pharmacy, emergency hospital, and clinic locator routing.',
    url: 'https://www.openstreetmap.org/',
    status: 'online',
    itemsCount: '10B+ nodes',
  },

  // 4. Planetary & Environment
  {
    id: 'nasa-rss',
    name: 'NASA News & RSS Feeds',
    category: 'Planetary & Environment',
    description: 'Aeronautics, space exploration, and space medicine physiological radiation studies.',
    url: 'https://www.nasa.gov/rss-feeds/',
    status: 'online',
    itemsCount: 'Live RSS feeds',
  },
  {
    id: 'nasa-data',
    name: 'NASA Open Data Portal',
    category: 'Planetary & Environment',
    description: 'Atmospheric telemetry, space biology research, and earth observation science.',
    url: 'https://data.nasa.gov/',
    status: 'online',
    itemsCount: '32K+ datasets',
  },
  {
    id: 'noaa-data',
    name: 'NOAA Weather & Climate Data',
    category: 'Planetary & Environment',
    description: 'Oceanic and atmospheric data monitoring temperature effects on medication shelf-life and stability.',
    url: 'https://www.noaa.gov/data',
    status: 'online',
    itemsCount: 'Peta-scale feeds',
  },
  {
    id: 'usgs-earthquakes',
    name: 'USGS Real-time Feeds',
    category: 'Planetary & Environment',
    description: 'Real-time global seismic monitoring ensuring hospital emergency pharmaceutical preparedness.',
    url: 'https://earthquake.usgs.gov/earthquakes/feed/',
    status: 'online',
    itemsCount: 'Real-time JSON/GeoJSON',
  },
  {
    id: 'openaq',
    name: 'OpenAQ Air Quality Data',
    category: 'Planetary & Environment',
    description: 'Global ambient air quality metrics analyzing respiratory medication efficacy under pollution.',
    url: 'https://openaq.org/',
    status: 'online',
    itemsCount: '1.2B+ measurements',
  },
  {
    id: 'open-meteo',
    name: 'Open-Meteo Weather API',
    category: 'Planetary & Environment',
    description: 'Open-source global weather forecasts for humidity and temperature medicine storage safety.',
    url: 'https://open-meteo.com/',
    status: 'online',
    itemsCount: 'High-res weather API',
  },
];
